name: iNet_gt
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - anndata=0.9.2
  - anyio=3.7.1
  - appdirs=1.4.4
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - arrow-cpp=11.0.0
  - astor=0.8.1
  - asttokens=2.4.1
  - atk-1.0=2.38.0
  - attrs=23.2.0
  - autograd=1.6.2
  - autograd-gamma=0.5.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - beautifulsoup4=4.12.3
  - biopython=1.83
  - bioservices=1.11.2
  - bleach=6.1.0
  - blinker=1.7.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cairomm-1.16=1.16.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - colorlog=6.8.2
  - colour=0.1.5
  - comm=0.2.1
  - contourpy=1.1.1
  - cycler=0.12.1
  - dash=2.15.0
  - dash-bio=1.0.2
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - easydev=0.12.0
  - entrypoints=0.4
  - epoxy=1.5.10
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - flask=3.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - formulaic=1.0.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=1.0.0
  - gdk-pixbuf=2.42.10
  - geoparse=2.0.3
  - gettext=0.21.1
  - gevent=23.9.0.post1
  - gflags=2.2.2
  - glib-tools=2.78.0
  - glog=0.5.0
  - glpk=5.0
  - gmp=6.2.1
  - graph-tool=2.58
  - graph-tool-base=2.58
  - graphite2=1.3.13
  - graphlib-backport=1.0.3
  - greenlet=3.0.3
  - grequests=0.6.0
  - grpc-cpp=1.48.2
  - gtk3=3.24.38
  - h5py=3.10.0
  - harfbuzz=8.2.1
  - hdf5=1.14.2
  - hicolor-icon-theme=0.17
  - html5lib=1.1
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_resources=6.1.2
  - interface_meta=1.3.0
  - ipykernel=6.23.3
  - ipython=8.22.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - itsdangerous=2.1.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.7.1
  - jupyter_server=1.24.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.10
  - kaleido-core=0.2.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.3.0
  - libcxx=15.0.7
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgirepository=1.78.1
  - libglib=2.78.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.26
  - libpng=1.6.43
  - libprotobuf=3.20.3
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.6.0
  - libuv=1.47.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.6
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lifelines=0.27.7
  - llvm-openmp=17.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - mathjax=2.7.7
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - metis=5.1.0
  - mistune=3.0.2
  - mpfr=4.2.1
  - multiprocess=0.70.14
  - munkres=1.1.4
  - natsort=8.4.0
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.16.1
  - nbconvert-core=7.16.1
  - nbconvert-pandoc=7.16.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=6.5.5
  - notebook-shim=0.2.4
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.3.0
  - orc=1.7.4
  - packaging=23.2
  - pandas=2.0.3
  - pandoc=3.1.12.1
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parmed=4.1.0
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.40
  - periodictable=1.5.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - plotly=5.19.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycairo=1.24.0
  - pycparser=2.21
  - pygments=2.17.2
  - pygobject=3.46.0
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-igraph=0.10.6
  - python-kaleido=0.2.1
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyzmq=23.2.0
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests_cache=0.4.13
  - retrying=1.3.3
  - scikit-learn=1.3.1
  - scikit-posthocs=0.9.0
  - scipy=1.12.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.2
  - setuptools=69.1.1
  - sigcpp-3.0=3.6.0
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - sparsehash=2.0.4
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - suds-community=1.1.2
  - suitesparse=5.10.1
  - tbb=2021.11.0
  - tenacity=8.2.3
  - terminado=0.18.0
  - texttable=1.7.0
  - threadpoolctl=3.3.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.1
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - widgetsnbextension=4.0.10
  - wrapt=1.16.0
  - xmltodict=0.13.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zope.event=5.0
  - zope.interface=6.2
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
    - click==8.1.3
    - fastjsonschema==2.17.1
    - fuzzy-c-means==1.7.0
    - gravis==0.1.0
    - gseapy==1.1.3
    - jsonschema==4.18.0
    - jsonschema-specifications==2023.6.1
    - kaplanmeier==0.2.0
    - nbformat==5.9.0
    - pydantic==1.10.10
    - referencing==0.29.1
    - rpds-py==0.8.8
    - tabulate==0.8.10
    - tqdm==4.65.0
    - typer==0.4.2
